codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    enable: false

comment:
  layout: "header, diff, flags, files"
  behavior: "default"
  require_changes: false

flags:
  unittests:
    paths:
      - "tests/"
    carryforward: false

github_checks:
  annotations: true